### ISSUE TITLE
Lab1 Unable to deploy

### ISSUE THREAD

**Issue by manurawat** [aws-samples/aws-serverless-saas-workshop#67]
Hi Team,

Getting below error while deployment Lab1

![image](https://github.com/aws-samples/aws-serverless-saas-workshop/assets/86109086/00eb5ce5-8ca4-4d66-9c7b-53e0916ea935)

Looks like template needs to be updated to create a role first. any suggestions?

**Comment by manurawat** [comment]
Hi @ujwalbukka , Thanks for your prompt response. Getting different error now

![image](https://github.com/aws-samples/aws-serverless-saas-workshop/assets/86109086/3e8e5e75-300e-4b86-ba9b-78f12d648ede)

**Comment by ujwalbukka** [comment]
I think it might be a format issue, as highlighted below at line 297 add a tab space so that is aligns with other resources.

![Snip20240418_3](https://github.com/aws-samples/aws-serverless-saas-workshop/assets/63979260/5fad79b2-6e07-49e0-a6ad-9689b94e4fc2)

You can also just take the above code in the [comment](https://github.com/aws-samples/aws-serverless-saas-workshop/issues/67#issuecomment-2064052587) and put it in a different CFN template and deploy it too.

**Comment by manurawat** [comment]
@ujwalbukka Thank you for the help. It works.
